# pacman
[[package_managers]]
name = "pacman"

[package_managers.install_command]
command = "sudo"
args = ["pacman", "-S", "--needed"]

[package_managers.list_command]
command = "pacman"
args = ["-Qqen"]

# duplicate pacman
[[package_managers]]
name = "pacman"

[package_managers.install_command]
command = "sudo"
args = ["pacman", "-S", "--needed"]

[package_managers.list_command]
command = "pacman"
args = ["-Qqen"]
