# this is a temporary file that should get moved to dotfiles/

# pacman
[[package_managers]]
name = "pacman"

[package_managers.install_command]
command = "sudo"
args = ["pacman", "-S", "--needed", "--noconfirm"]

[package_managers.list_command]
command = "pacman"
args = ["-Qqen"]

# yay
[[package_managers]]
name = "yay"

[package_managers.install_command]
command = "yay"
args = ["-S", "--needed"]

[package_managers.list_command]
command = "pacman"
args = ["-Qqm"]

# entry for shitty ass package manager
[[package_managers]]
name = "shitty ass package manager"

[package_managers.install_command]
command = ""
args = []

[package_managers.list_command]
command = ""
args = []


# entry for shitty ass package manager
[[package_managers]]
name = "shitty ass package manager"

[package_managers.install_command]
command = ""
args = []

[package_managers.list_command]
command = ""
args = []
