# entry for test1
[[package_managers]]
name = "test1"

[package_managers.install_command]
command = ""
args = []

[package_managers.list_command]
command = ""
args = []


# entry for test2
[[package_managers]]
name = "test2"

[package_managers.install_command]
command = ""
args = []

[package_managers.list_command]
command = ""
args = []
